### ISSUE TITLE
Don't disable mirrors silently

### ISSUE THREAD

**Issue by abompard** [fedora-infra/mirrormanager2#342] opened 2024-06-03 13:36 UTC
At the moment, mirrors are disabled after a threshold of consecutive crawl failures. This does not cause an email to be sent, or a message to be emitted. Mirrors should not be disabled (or re-enabled) silently.
Mirrormanager could send a Fedora Message that would be sent out as a notification by FMN. The "robot_email" column could also be used to send an email directly.

**Comment by ryanlerch** [comment] 2024-07-09 03:10
Duplicate of #246

**Closed by ryanlerch** 2024-07-09 03:10 UTC
Labels: enhancement, easyfix
